### ISSUE TITLE
[Feat] 요약 및 문제 생성 API 구현

### ISSUE THREAD

**Issue by hynseoj** [kakao-tech-campus-2nd-step3/Team29_BE#14]
## 🖍️ 기능 설명

> 추가하려는 기능에 대해 간결하게 설명해주세요
+ 강의자료 ID 와 페이지 번호 리스트(옵션)로 요약 및 문제 생성 요청을 하면 AI 서버에 요청을 보내고, 접수되었음을 응답하는 기능 구현

_실제 AI 서버와 통신하는 부분은 추후 구현_

## 🔎 작업 상세 내용

- [x] 강의자료 존재 여부를 확인하고, 요약, 문제 및 작업 레코드를 생성 후 저장

**Comment by Kami-prog** [comment]
maybe this will help
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
If you don't have the c compliator, install it.(gcc or clang)
